[package]
name = "caracal_contracts"
version = "0.1.0"
edition = "2023_11"

[[target.starknet-contract]]
sierra = true

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.6.4"
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git" }
