[package]
name = "sunya"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.6.4"
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git" }

[[target.starknet-contract]]
sierra = true

[cairo]
sierra-replace-ids = true