[package]
name = "sunya"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.6.3"
authors = ["Lexy <not.so.lexy@gmail.com>", "codemonkey-sagar <fmtsagar@gmail.com>"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[[target.starknet-contract]]
sierra = true

[tool.voyager]
my_contract = { path = "lib.cairo" }